# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-04 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
