# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-04 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0002_user_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votes',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='buyhatke',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='cleartax',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='helpchat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='recipebook',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='signeasy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='strike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='volt',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='votes',
        ),
    ]
